# Uses VS Code Rest Client extension
@baseurl = http://localhost:3000/api

### Get all blogs
GET {{baseurl}}/blogs HTTP/1.1

### Get blog by ID
GET {{baseurl}}/blog/7 HTTP/1.1

### Get all users
GET {{baseurl}}/users HTTP/1.1

### Add Blog
POST {{baseurl}}/blogs HTTP/1.1
Content-Type: application/json

{
  "data":
    {
      "title": "My New Blog 3",
      "body": "This is the body of the blog post",
      "authorId": "cl72pfbk50006kwo17813t56u"
    }
}

### Update blog
PUT {{baseurl}}/blogs HTTP/1.1
Content-Type: application/json

{
  "data":
    {
      "title": "this blog has been editedx",
      "body": "xx oo",
      "id": 2
    }
}

### Delete blog
DELETE {{baseurl}}/blogs HTTP/1.1
Content-Type: application/json

{
  "data":
    {
      "id": 33
    }
}

### Search blogs
POST {{baseurl}}/blog/search HTTP/1.1
Content-Type: application/json

{
  "search":
    {
      "term": "apollo"
    }
}
