const blogs = [
  {
    title: 'Zeus, God of the Sky',
    authorId: 'cl72rfacf0047p9o1z9hgk542',
    body: "Zeus is the sky and thunder god in ancient Greek religion, who rules as king of the gods of Mount Olympus. His name is cognate with the first element of his Roman equivalent Jupiter. His mythology and powers are similar, though not identical, to those of Indo-European deities such as Jupiter, Perkūnas, Perun, Indra, Dyaus and Thor.  Zeus is the child of Cronus and Rhea, the youngest of his siblings to be born, though sometimes reckoned the eldest as the others required disgorging from Cronus's stomach. In most traditions, he is married to Hera, by whom he is usually said to have fathered Ares, Hebe, and Hephaestus. At the oracle of Dodona, his consort was said to be Dione, by whom the Iliad states that he fathered Aphrodite. Zeus was also infamous for his erotic escapades. These resulted in many divine and heroic offspring, including Athena, Apollo, Artemis, Hermes, Persephone, Dionysus, Perseus, Heracles, Helen of Troy, Minos, and the Muses.",
  },
  {
    title: 'Hera, Goddess of Women, Marriage, Family and Childbirth',
    authorId: 'cl72pfbk50006kwo17813t56u',
    body: "Hera is the goddess of women, marriage, family and childbirth in ancient Greek religion and mythology, one of the twelve Olympians and the sister and wife of Zeus. She is the daughter of the Titans Cronus and Rhea. Hera rules over Mount Olympus as queen of the gods. A matronly figure, Hera served as both the patroness and protectress of married women, presiding over weddings and blessing marital unions. One of Hera's defining characteristics is her jealous and vengeful nature against Zeus' numerous lovers and illegitimate offspring, as well as the mortals who cross her.  Hera on an antique fresco from Pompeii Hera is commonly seen with the animals she considers sacred, including the cow, lion and the peacock. Portrayed as majestic and solemn, often enthroned, and crowned with the polos (a high cylindrical crown worn by several of the Great Goddesses), Hera may hold a pomegranate in her hand, emblem of fertile blood and death and a substitute for the narcotic capsule of the opium poppy.",
  },
  {
    title: 'Poseidon, God of the Sea',
    authorId: 'cl72s17050213p9o13751opr9',
    body: "Poseidon was one of the Twelve Olympians in ancient Greek religion and myth, god of the sea, storms, earthquakes and horses. In pre-Olympian Bronze Age Greece, he was venerated as a chief deity at Pylos and Thebes. He had also the cult title 'earth shaker'. In the myths of isolated Arcadia he is related with Demeter and Persephone and he was venerated as a horse, however it seems that he was originally a god of the waters. He is often regarded as the tamer or father of horses, and with a strike of his trident, he created springs which are related with the word horse. His Roman equivalent is Neptune.  Poseidon was protector of seafarers, and of many Hellenic cities and colonies. Homer and Hesiod suggest that Poseidon became lord of the sea following the defeat of his father Cronus, when the world was divided by lot among his three sons; Zeus was given the sky, Hades the underworld, and Poseidon the sea, with the Earth and Mount Olympus belonging to all three. In Homer's Iliad, Poseidon supports the Greeks against the Trojans during the Trojan War and in the Odyssey, during the sea-voyage from Troy back home to Ithaca, the Greek hero Odysseus provokes Poseidon's fury by blinding his son, the Cyclops Polyphemus, resulting in Poseidon punishing him with storms, the complete loss of his ship and companions, and a ten-year delay. Poseidon is also the subject of a Homeric hymn. In Plato's Timaeus and Critias, the legendary island of Atlantis was Poseidon's domain.",
  },
  {
    title: 'Demeter, Goddess of Harvest, Grain, and Fertility',
    authorId: 'cl72rfacf0047p9o1z9hgk542',
    body: "Demeter is the Olympian goddess of the harvest and agriculture, presiding over grains and the fertility of the earth. She was also called Deo. Her cult titles include Sito, 'she of the Grain', as the giver of food or grain, and Thesmophoros, 'giver of customs' or 'legislator', in association with the secret female-only festival called the Thesmophoria.  Though Demeter is often described simply as the goddess of the harvest, she presided also over the sacred law, and the cycle of life and death. She and her daughter Persephone were the central figures of the Eleusinian Mysteries, a religious tradition that predated the Olympian pantheon, and which may have its roots in the Mycenaean period c. 1400–1200 BC.",
  },
  {
    title: 'Ares, God Courage of War',
    authorId: 'cl72s17050213p9o13751opr9',
    body: "Ares is the Greek god of courage and war. He is one of the Twelve Olympians, and the son of Zeus and Hera. The Greeks were ambivalent toward him. He embodies the physical valor necessary for success in war but can also personify sheer brutality and bloodlust, in contrast to his sister, the armored Athena, whose martial functions include military strategy and generalship. An association with Ares endows places and objects with a savage, dangerous, or militarized quality.  Although Ares' name shows his origins as Mycenaean, his reputation for savagery was thought by some to reflect his likely origins as a Thracian deity. Some cities in Greece and several in Asia Minor held annual festivals to bind and detain him as their protector. In parts of Asia Minor he was an oracular deity. Still further away from Greece, the Scythians were said to ritually kill one in a hundred prisoners of war as an offering to their equivalent of Ares, but the later belief that ancient Spartans had offered human sacrifice to Ares may owe more to mythical prehistory and misunderstandings than to reality.",
  },
  {
    title: 'Athena,Goddess of Wisdom and War',
    authorId: 'cl72s0uzu0177p9o1nn6ah7n1',
    body: "Athena or Athene, often given the epithet Pallas, is an ancient Greek goddess associated with wisdom, handicraft, and warfare who was later syncretized with the Roman goddess Minerva. Athena was regarded as the patron and protectress of various cities across Greece, particularly the city of Athens, from which she most likely received her name. The Parthenon on the Acropolis of Athens is dedicated to her. Her major symbols include owls, olive trees, snakes, and the Gorgoneion. In art, she is generally depicted wearing a helmet and holding a spear.  From her origin as an Aegean palace goddess, Athena was closely associated with the city. She was known as Polias and Poliouchos (both derived from polis, meaning 'city-state'), and her temples were usually located atop the fortified acropolis in the central part of the city. The Parthenon on the Athenian Acropolis is dedicated to her, along with numerous other temples and monuments. As the patron of craft and weaving, Athena was known as Ergane. She was also a warrior goddess, and was believed to lead soldiers into battle as Athena Promachos. Her main festival in Athens was the Panathenaia, which was celebrated during the month of Hekatombaion in midsummer and was the most important festival on the Athenian calendar.",
  },
  {
    title:
      'Apollo, God of archery, Music and Dance, Truth and Prophecy, Healing and Diseases',
    authorId: 'cl72rfacf0047p9o1z9hgk542',
    body: "Apollo is one of the Olympian deities in classical Greek and Roman religion and Greek and Roman mythology. The national divinity of the Greeks, Apollo has been recognized as a god of archery, music and dance, truth and prophecy, healing and diseases, the Sun and light, poetry, and more. One of the most important and complex of the Greek gods, he is the son of Zeus and Leto, and the twin brother of Artemis, goddess of the hunt. Seen as the most beautiful god and the ideal of the kouros (ephebe, or a beardless, athletic youth), Apollo is considered to be the most Greek of all the gods. Apollo is known in Greek-influenced Etruscan mythology as Apulu.  As the patron deity of Delphi (Apollo Pythios), Apollo is an oracular god—the prophetic deity of the Delphic Oracle. Apollo is the god who affords help and wards off evil; various epithets call him the 'averter of evil'. Delphic Apollo is the patron of seafarers, foreigners and the protector of fugitives and refugees.  Medicine and healing are associated with Apollo, whether through the god himself or mediated through his son Asclepius. Apollo delivered people from epidemics, yet he is also a god who could bring ill-health and deadly plague with his arrows. The invention of archery itself is credited to Apollo and his sister Artemis. Apollo is usually described as carrying a golden bow and a quiver of silver arrows. Apollo's capacity to make youths grow is one of the best attested facets of his panhellenic cult persona. As the protector of young (kourotrophos), Apollo is concerned with the health and education of children. He presided over their passage into adulthood. Long hair, which was the prerogative of boys, was cut at the coming of age (ephebeia) and dedicated to Apollo.",
  },
  {
    title: 'Artemis, Goddess of the Moon, the Hunt, and Young Maidens',
    authorId: 'cl72pfbk50006kwo17813t56u',
    body: "Artemis is the Greek goddess of the hunt, the wilderness, wild animals, the Moon, and chastity. The goddess Diana is her Roman equivalent. Artemis is the daughter of Zeus and Leto, and the twin sister of Apollo. She was the patron and protector of young girls, and was believed to both bring disease upon women and relieve them of it. Artemis was worshipped as one of the primary goddesses of childbirth and midwifery along with Eileithyia. Much like Athena and Hestia, Artemis preferred to remain a maiden and was sworn never to marry.  Artemis was one of the most widely venerated of the Ancient Greek deities, and her temple at Ephesus was one of the Seven Wonders of the Ancient World. Artemis' symbols included a bow and arrow, a quiver, and hunting knives, and the deer and the cypress were sacred to her. Diana, her Roman equivalent, was especially worshipped on the Aventine Hill in Rome, near Lake Nemi in the Alban Hills, and in Campania.",
  },
  {
    title: 'Hephaestus, God of blacksmiths, carpenters, artisans and sculptors',
    authorId: 'cl72s0uzu0177p9o1nn6ah7n1',
    body: "Hephaestus is the Greek god of blacksmiths, metalworking, carpenters, craftsmen, artisans, sculptors, metallurgy, fire (compare, however, with Hestia), and volcanoes. Hephaestus's Roman counterpart is Vulcan. In Greek mythology, Hephaestus was either the son of Zeus and Hera or he was Hera's parthenogenous child. He was cast off Mount Olympus by his mother because of a congenital impairment or, in another account, by Zeus for protecting Hera from his advances.  As a smithing god, Hephaestus made all the weapons of the gods in Olympus. He served as the blacksmith of the gods, and was worshipped in the manufacturing and industrial centres of Greece, particularly Athens. The cult of Hephaestus was based in Lemnos. Hephaestus's symbols are a smith's hammer, anvil, and a pair of tongs.",
  },
  {
    title: 'Aphrodite, Goddess of Sexual Love and Beauty',
    authorId: 'cl72s17050213p9o13751opr9',
    body: "Aphrodite is an ancient Greek goddess associated with love, beauty, pleasure, passion and procreation. She was syncretized with the Roman goddess Venus. Aphrodite's major symbols include myrtles, roses, doves, sparrows, and swans. The cult of Aphrodite was largely derived from that of the Phoenician goddess Astarte, a cognate of the East Semitic goddess Ishtar, whose cult was based on the Sumerian cult of Inanna. Aphrodite's main cult centers were Cythera, Cyprus, Corinth, and Athens. Her main festival was the Aphrodisia, which was celebrated annually in midsummer. In Laconia, Aphrodite was worshipped as a warrior goddess. She was also the patron goddess of prostitutes, an association which led early scholars to propose the concept of 'sacred prostitution' in Greco-Roman culture, an idea which is now generally seen as erroneous.  In Hesiod's Theogony, Aphrodite is born off the coast of Cythera from the foam produced by Uranus's genitals, which his son Cronus has severed and thrown into the sea. In Homer's Iliad, however, she is the daughter of Zeus and Dione. Plato, in his Symposium 180e, asserts that these two origins actually belong to separate entities: Aphrodite Ourania (a transcendent, 'Heavenly' Aphrodite) and Aphrodite Pandemos (Aphrodite common to 'all the people'). Aphrodite had many other epithets, each emphasizing a different aspect of the same goddess, or used by a different local cult. Thus she was also known as Cytherea (Lady of Cythera) and Cypris (Lady of Cyprus), because both locations claimed to be the place of her birth.",
  },
  {
    title: 'God of the Roadways, Travelers, Merchants and Thieves',
    authorId: 'cl72pfbk50006kwo17813t56u',
    body: "Hermes is an Olympian deity in ancient Greek religion and mythology. Hermes is considered the herald of the gods. He is also considered the protector of human heralds, travellers, thieves, merchants, and orators. He is able to move quickly and freely between the worlds of the mortal and the divine, aided by his winged sandals. Hermes plays the role of the psychopomp or 'soul guide'—a conductor of souls into the afterlife. In myth, Hermes functioned as the emissary and messenger of the gods, and was often presented as the son of Zeus and Maia, the Pleiad. He is regarded as 'the divine trickster,' for which Homer offers the most popular account in his Hymn to Hermes.  His attributes and symbols include the herma, the rooster, the tortoise, satchel or pouch, talaria (winged sandals), and winged helmet or simple petasos, as well as the palm tree, goat, the number four, several kinds of fish, and incense. However, his main symbol is the caduceus, a winged staff intertwined with two snakes copulating and carvings of the other gods. His attributes had previously influenced the earlier Etruscan god Turms, a name borrowed from the Greek 'herma'.",
  },
  {
    title: 'Dionysus, God of Grape-harvest, Winemaking and Wine',
    authorId: 'cl72s0uzu0177p9o1nn6ah7n1',
    body: "Dionysus is the god of the grape-harvest, winemaking and wine, of fertility, orchards and fruit, vegetation, insanity, ritual madness, religious ecstasy, festivity and theatre in ancient Greek religion and myth. He is also known as Bacchus, the name adopted by the Romans; the frenzy he induces is bakkheia. Another name used by the Romans is Liber meaning 'free', due to his association with wine and the Bacchanalia and other rites, and the freedom associated with it. His thyrsus, sometimes wound with ivy and dripping with honey, is both a beneficent wand and a weapon used to destroy those who oppose his cult and the freedoms he represents. As Eleutherios ('the liberator'), his wine, music and ecstatic dance free his followers from self-conscious fear and care, and subvert the oppressive restraints of the powerful. Those who partake of his mysteries are believed to become possessed and empowered by the god himself.  In his religion, identical with or closely related to Orphism, Dionysus was believed to have been born from the union of Zeus and Persephone, and to have himself represented a chthonic or underworld aspect of Zeus. Many believed that he had been born twice, having been killed and reborn as the son of Zeus and the mortal Semele. In the Eleusinian Mysteries he was identified with Iacchus, the son (or, alternately, husband) of Demeter.",
  },
  {
    title: 'Hades, God of the Underworld',
    authorId: 'cl72rfacf0047p9o1z9hgk542',
    body: "Hades, in the ancient Greek religion and myth, is the god of the dead and the king of the underworld, with which his name became synonymous. Hades was the eldest son of Cronus and Rhea, although this also made him the last son to be regurgitated by his father. He and his brothers, Zeus and Poseidon, defeated their father's generation of gods, the Titans, and claimed rulership over the cosmos. Hades received the underworld, Zeus the sky, and Poseidon the sea, with the solid earth, long the province of Gaia, available to all three concurrently. In artistic depictions, Hades is typically portrayed holding a bident and wearing his helm with Cerberus, the three-headed guard dog of the underworld, standing to his side.  The Etruscan god Aita and the Roman gods Dis Pater and Orcus were eventually taken as equivalent to Hades and merged into Pluto, a Latinization of Plouton (Greek: Πλούτων, translit. Ploútōn), itself a euphemistic title often given to Hades.",
  },
  {
    title: 'Hypnos, God of Sleep',
    authorId: 'cl72pfbk50006kwo17813t56u',
    body: "In Greek mythology, Hypnos is the personification of sleep; the Roman equivalent is known as Somnus. His name is the origin of the word hypnosis. Hypnos is the son of Nyx ('The Night') and Erebus ('The Darkness'). His brother is Thanatos ('Death'). Both siblings live in the underworld (Hades) or in Erebus, another valley of the Greek underworld. According to rumors, Hypnos lived in a big cave, which the river Lethe ('Forgetfulness') comes from and where night and day meet. His bed is made of ebony, on the entrance of the cave grow a number of poppies and other soporific plants. No light and no sound would ever enter his grotto. According to Homer, he lives on the island Lemnos, which later on has been claimed to be his very own dream-island. He is said to be a calm and gentle god, as he helps humans in need and, due to their sleep, owns half of their lives.  Hypnos lived next to his twin brother, Thanatos in the underworld. Hypnos' mother was Nyx, the deity of Night, and his father was Erebus, the deity of Darkness. Nyx was a dreadful and powerful goddess, and even Zeus feared to enter her realm. His wife, Pasithea, was one of the youngest of the Charites and was promised to him by Hera, who is the goddess of marriage and birth. Pasithea is the deity of hallucination or relaxation.",
  },
  {
    title: 'Nike, Goddess of Victory',
    authorId: 'cl72s0uzu0177p9o1nn6ah7n1',
    body: 'In ancient Greek civilization, Nike was a goddess who personified victory. Her Roman equivalent was Victoria. Nike is the daughter of the Titan Pallas and the goddess Styx, and the sister of Kratos (Strength), Bia (Force), and Zelus (Zeal). And Styx the daughter of Ocean was joined to Pallas and bore Zelus (Emulation) and trim-ankled Nike (Victory) in the house. Also she brought forth Kratos (Strength) and Bia (Force), wonderful children.  Nike and her siblings were close companions of Zeus, the dominant deity of the Greek pantheon. According to classical (later) myth, Styx brought them to Zeus when the god was assembling allies for the Titanomachy against the older deities. Nike assumed the role of the divine charioteer, a role in which she often is portrayed in Classical Greek art. Nike flew around battlefields rewarding the victors with glory and fame, symbolized by a wreath of laurel leaves (bay leaves).',
  },
  {
    title: 'Janus, God of Beginnings and Transitions',
    authorId: 'cl72rfacf0047p9o1z9hgk542',
    body: "In ancient Roman religion and myth, Janus (/ˈdʒeɪnəs/ JAY-nəs; Latin: Ianus ) is the god of beginnings, gates, transitions, time, duality, doorways, passages, frames, and endings. He is usually depicted as having two faces. It is conventionally thought that the month of January is named for Janus (Ianuarius), but according to ancient Roman farmers' almanacs Juno was the tutelary deity of the month.  Janus presided over the beginning and ending of conflict, and hence war and peace. The gates of a building in Rome named after him (not a temple, as it is often called, but an open enclosure with gates at each end) were opened in time of war, and closed to mark the arrival of peace. As a god of transitions, he had functions pertaining to birth and to journeys and exchange, and in his association with Portunus, a similar harbor and gateway god, he was concerned with travelling, trading and shipping.",
  },
  {
    title: 'Nemesis, Goddess of Revenge',
    authorId: 'cl72s17050213p9o13751opr9',
    body: "In ancient Greek religion, Nemesis, also called Rhamnousia or Rhamnusia, is the goddess who enacts retribution against those who succumb to hubris, arrogance before the gods. The name Nemesis is related to the Greek word νέμειν némein, meaning 'to give what is due', from Proto-Indo-European nem- 'distribute'. Divine retribution is a major theme in the Hellenic world view, providing the unifying theme of the tragedies of Sophocles and many other literary works. Hesiod states: 'Also deadly Nyx bore Nemesis an affliction to mortals subject to death' (Theogony, 223, though perhaps an interpolated line). Nemesis appears in a still more concrete form in a fragment of the epic Cypria.  She is implacable justice: that of Zeus in the Olympian scheme of things, although it is clear she existed prior to him, as her images look similar to several other goddesses, such as Cybele, Rhea, Demeter, and Artemis. As the 'Goddess of Rhamnous', Nemesis was honored and placated in an archaic sanctuary in the isolated district of Rhamnous, in northeastern Attica. There she was a daughter of Oceanus, the primeval river-ocean that encircles the world. Pausanias noted her iconic statue there. It included a crown of stags and little Nikes and was made by Pheidias after the Battle of Marathon (490 BC), crafted from a block of Parian marble brought by the overconfident Persians, who had intended to make a memorial stele after their expected victory. Her cult may have originated at Smyrna.",
  },
  {
    title: 'Iris, Goddess of the Rainbow',
    authorId: 'cl72s0uzu0177p9o1nn6ah7n1',
    body: "In Greek mythology, Iris is a daughter of the gods Thaumas and Electra, the personification and goddess of the rainbow and messenger of the gods. Iris is the daughter of Thaumas and the Oceanid Electra and the sister of the Harpies: Aello and Ocypete. During the Titanomachy, Iris was the messenger of the Olympian gods while her sister Arke betrayed the Olympians and became the messenger of the Titans. She is the goddess of the rainbow. She also serves nectar to the goddesses and gods to drink. Zephyrus, who is the god of the west wind is her consort. Together they had a son named Pothos, or alternatively they were the parents of Eros, the god of love, according to sixth century BC Greek lyric poet Alcaeus, though Eros is usually said to be the son of Ares and Aphrodite. According to the Dionysiaca of Nonnus, Iris' brother is Hydaspes.  She is also known as one of the goddesses of the sea and the sky. Iris links the gods to humanity. She travels with the speed of wind from one end of the world to the other and into the depths of the sea and the underworld.  In some records Iris is a sister to fellow messenger goddess Arke (arch), who flew out of the company of Olympian gods to join the Titans as their messenger goddess during the Titanomachy, making the two sisters enemy messenger goddesses. Iris was said to have golden wings, whereas Arke had iridescent ones. She is also said to travel on the rainbow while carrying messages from the gods to mortals. During the Titan War, Zeus tore Arke's iridescent wings from her and gave them as a gift to the Nereid Thetis at her wedding, who in turn gave them to her son, Achilles, who wore them on his feet. Achilles was sometimes known as podarkes (feet like wings of] Arke). Podarces was also the original name of Priam, king of Troy.",
  },
  {
    title: 'Hecate, Goddess of Magic, Crossroads and Ghosts',
    authorId: 'cl72rfacf0047p9o1z9hgk542',
    body: "Hecate is a goddess in ancient Greek religion and mythology, most often shown holding a pair of torches, a key, snakes or accompanied by dogs and in later periods depicted in triple form. She is variously associated with crossroads, entrance-ways, night, light, magic, witchcraft, knowledge of herbs and poisonous plants, ghosts, necromancy, and sorcery. Her earliest appearance in literature was in Hesiod's Theogony in the 8th century BCE as a goddess of great honor with domains in sky, earth, and sea. Her place of origin is debated by scholars, but she had popular followings amongst the witches of Thessaly and an important sanctuary among the Carian Greeks of Asia Minor in Lagina.  Hecate was one of several deities worshipped in ancient Athens as a protector of the oikos (household), alongside Zeus, Hestia, Hermes, and Apollo. In the post-Christian writings of the Chaldean Oracles (2nd–3rd century CE) she was also regarded with (some) rulership over earth, sea, and sky, as well as a more universal role as Savior (Soteira), Mother of Angels and the Cosmic World Soul. Regarding the nature of her cult, it has been remarked, 'she is more at home on the fringes than in the center of Greek polytheism. Intrinsically ambivalent and polymorphous, she straddles conventional boundaries and eludes definition.",
  },
  {
    title: 'Tyche, Goddess of Good Luck and Fortune',
    authorId: 'cl72pfbk50006kwo17813t56u',
    body: "Tyche was the presiding tutelary deity who governed the fortune and prosperity of a city, its destiny. In Classical Greek mythology, she is the daughter of Aphrodite and Zeus or Hermes. The Greek historian Polybius believed that when no cause can be discovered to events such as floods, droughts, frosts, or even in politics, then the cause of these events may be fairly attributed to Tyche. Increasingly during the Hellenistic period, cities venerated their own Tychai, specific iconic versions of the original Tyche. This practice was continued in the iconography of Roman art, even into the Christian period, often as sets of the greatest cities of the empire.  In literature, Tyche might be given various genealogies, as a daughter of Hermes and Aphrodite, or considered one of the Oceanids, daughters of Oceanus, and Tethys, or of Zeus. She was connected with Nemesis and Agathos Daimon. She's sometimes named as the mother of Plutus, the god of wealth; usually, however, he is the son of Demeter and Iasion. Tyche was uniquely venerated at Itanos in Crete, as Tyche Protogeneia, linked with the Athenian Protogeneia, daughter of Erechtheus, whose self-sacrifice saved the city. In Alexandria the Tychaeon, the Greek temple of Tyche, was described by Libanius as one of the most magnificent of the entire Hellenistic world.",
  },
]

export default blogs
